// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createViewRegistry } from "../ui/views.ts";
import * as view0 from "./data-table/tui.ts";

export const views = createViewRegistry({
	modules: {
		"data-table": view0,
	},
	panelTitles: {
		"data-table": "latest table"
	},
	views: [
		{
			"id": "data-table",
			"shows": [
				"forge_*"
			]
		}
	],
});

/** Wrap a tool definition so results with details.view render as that view. */
export const withViews = views.withViews;
export { viewResult } from "./contract.ts";
