// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createPlan } from "../forge_modules/plan/plan.ts";

export default createPlan();
