// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createHeader } from "../forge_modules/ui/header.ts";

export default createHeader({
	"name": "chem",
	"title": "Chem Lab",
	"description": "Chemistry research assistant with PubChem tools and molecule views",
	"hint": "Try: find molecules similar to aspirin",
	"art": [
		"    ___",
		"   /   \\",
		"  | ( ) |",
		"   \\___/"
	]
});
