// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createViewRegistry } from "../ui/views.ts";
import * as view0 from "./molecule/tui.ts";
import * as view1 from "./data-table/tui.ts";

export const views = createViewRegistry({
	modules: {
		"molecule": view0,
		"data-table": view1,
	},
	panelTitles: {
		"molecule": "current molecule",
		"data-table": "latest table"
	},
	views: [
		{
			"id": "molecule",
			"shows": [
				"molecule_lookup"
			],
			"panel": "right"
		},
		{
			"id": "data-table",
			"shows": [
				"molecule_compare",
				"similar_molecules"
			]
		}
	],
});

/** Wrap a tool definition so results with details.view render as that view. */
export const withViews = views.withViews;
export { viewResult } from "./contract.ts";
