import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	type HarnessSpec,
	type Issue,
	readSpecFile,
	themeName,
	type ValidateContext,
	validateSpec,
} from "@forge/harness-spec";
import { createTwoFilesPatch, diffLines } from "diff";

export const GENERATOR_VERSION = "forge-gen@0.1.0";
export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
export const TEMPLATES_DIR = join(REPO_ROOT, "templates");

/** Version of pi installed in this checkout. */
export function installedPiVersion(): string | undefined {
	const file = join(REPO_ROOT, "node_modules", "@earendil-works", "pi-coding-agent", "package.json");
	return existsSync(file) ? (JSON.parse(readFileSync(file, "utf8")) as { version?: string }).version : undefined;
}

const MANIFEST = ".forge/manifest.json";
/** Folders and files the generator never writes or deletes. */
const PROTECTED = [/^custom\//, /^harness\.yaml$/, /^\.forge\//, /^node_modules\//];

const TS_BANNER = "// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.\n";
const copyBanner = (from: string) => `// Copied by forge from templates/${from}. Do not edit here: edit the template and regenerate.\n`;

// =============================================================================
// Types
// =============================================================================

export type ChangeKind = "add" | "update" | "delete" | "unchanged";

export interface Change {
	path: string;
	kind: ChangeKind;
	/** Set when applying would overwrite or delete something forge did not write. */
	conflict?: string;
	added: number;
	removed: number;
	patch?: string;
}

export interface GenPlan {
	harnessDir: string;
	spec?: HarnessSpec;
	issues: Issue[];
	files: Map<string, string>;
	changes: Change[];
}

interface Manifest {
	generator: string;
	files: Record<string, string>;
}

// =============================================================================
// Helpers
// =============================================================================

const normalize = (text: string) => text.replace(/\r\n/g, "\n");
const sha = (text: string) => createHash("sha256").update(normalize(text)).digest("hex").slice(0, 16);
const json = (value: unknown) => `${JSON.stringify(value, null, "\t")}\n`;
const tsString = (value: unknown) => JSON.stringify(value, null, "\t");

function readManifest(harnessDir: string): Manifest | undefined {
	const file = join(harnessDir, MANIFEST);
	if (!existsSync(file)) return undefined;
	return JSON.parse(readFileSync(file, "utf8")) as Manifest;
}

/** pi's built-in theme JSON. pi exports only an `import` entry, so locate the package folder directly. */
function piThemeFile(base: "dark" | "light"): string {
	const file = join(REPO_ROOT, "node_modules", "@earendil-works", "pi-coding-agent", "dist", "modes", "interactive", "theme", `${base}.json`);
	if (!existsSync(file)) throw new Error(`pi base theme not found: ${file}`);
	return file;
}

function listFiles(dir: string, prefix = ""): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
		if (entry.isDirectory()) out.push(...listFiles(join(dir, entry.name), rel));
		else out.push(rel);
	}
	return out;
}

// =============================================================================
// File plan: everything the harness folder should contain, derived from the spec
// =============================================================================

function planFiles(spec: HarnessSpec, harnessDir: string): Map<string, string> {
	const files = new Map<string, string>();
	const title = spec.title ?? spec.name;
	const copyTemplate = (from: string, to = `forge_modules/${from}`) => {
		const text = readFileSync(join(TEMPLATES_DIR, from), "utf8");
		files.set(to, from.endsWith(".ts") ? copyBanner(from) + normalize(text) : normalize(text));
	};

	// package.json: the harness folder is a pi package; bin starts it.
	const theme = spec.ui?.theme;
	const ownTheme = typeof theme === "object" || (typeof theme === "string" && existsSync(join(TEMPLATES_DIR, "themes", `${theme}.json`)));
	files.set(
		"package.json",
		json({
			name: `@forge/${spec.name}`,
			version: "0.1.0",
			private: true,
			type: "module",
			description: spec.description ?? `${title} (built with pi-Forge)`,
			keywords: ["pi-package"],
			bin: { [spec.name]: `./bin/${spec.name}.ts` },
			pi: {
				extensions: ["./extensions/*.ts", "./custom/extensions/*.ts"],
				skills: ["./custom/skills"],
				...(ownTheme ? { themes: ["./themes/*.json"] } : {}),
			},
			dependencies: { "@forge/harness-core": "*" },
		}),
	);

	files.set(
		`bin/${spec.name}.ts`,
		`#!/usr/bin/env node\n${TS_BANNER}import { dirname, join } from "node:path";\nimport { fileURLToPath } from "node:url";\nimport { runHarness } from "@forge/harness-core";\n\nawait runHarness(join(dirname(fileURLToPath(import.meta.url)), ".."));\n`,
	);

	// Theme: a named template theme is copied; an object spec derives one from pi's base theme.
	if (typeof theme === "object") {
		const base = JSON.parse(readFileSync(piThemeFile(theme.base), "utf8")) as {
			name: string;
			colors: Record<string, unknown>;
		};
		base.name = theme.name;
		base.colors.accent = theme.accent;
		base.colors.borderAccent = theme.accent;
		base.colors.border = theme.border ?? theme.accent;
		files.set(`themes/${theme.name}.json`, json(base));
	} else if (ownTheme && typeof theme === "string") {
		copyTemplate(`themes/${theme}.json`, `themes/${theme}.json`);
	}

	// Header (always): title, description, art.
	const artLib = JSON.parse(readFileSync(join(TEMPLATES_DIR, "ui", "art.json"), "utf8")) as Record<string, string[]>;
	copyTemplate("ui/header.ts");
	files.set(
		"extensions/forge-header.ts",
		`${TS_BANNER}import { createHeader } from "../forge_modules/ui/header.ts";\n\nexport default createHeader(${tsString({
			name: spec.name,
			title,
			description: spec.description,
			hint: spec.ui?.header?.hint,
			art: artLib[spec.ui?.header?.art ?? "none"] ?? [],
		})});\n`,
	);

	// Guards.
	if (spec.guards && ((spec.guards.protected_paths?.length ?? 0) > 0 || (spec.guards.confirm_bash?.length ?? 0) > 0)) {
		copyTemplate("guards/guards.ts");
		files.set(
			"extensions/forge-guards.ts",
			`${TS_BANNER}import { createGuards } from "../forge_modules/guards/guards.ts";\n\nexport default createGuards(${tsString({
				protectedPaths: spec.guards.protected_paths ?? [],
				confirmBash: spec.guards.confirm_bash ?? [],
			})});\n`,
		);
	}

	// Views: copy each template view, generate the registry (used by custom tools via withViews)
	// and the extension that pins panels.
	const views = spec.ui?.views ?? [];
	copyTemplate("views/contract.ts");
	copyTemplate("ui/views.ts");
	const imports: string[] = [];
	const modules: string[] = [];
	const panelTitles: Record<string, string> = {};
	views.forEach((view, i) => {
		const customDir = join(harnessDir, "custom", "views", view.id);
		const isCustom = existsSync(join(customDir, "view.json"));
		const viewDir = isCustom ? customDir : join(TEMPLATES_DIR, "views", view.id);
		if (!isCustom) for (const file of listFiles(viewDir)) copyTemplate(`views/${view.id}/${file}`);
		const meta = JSON.parse(readFileSync(join(viewDir, "view.json"), "utf8")) as { title?: string; panelTitle?: string };
		panelTitles[view.id] = meta.panelTitle ?? meta.title ?? view.id;
		const from = isCustom ? `../../custom/views/${view.id}/tui.ts` : `./${view.id}/tui.ts`;
		imports.push(`import * as view${i} from "${from}";`);
		modules.push(`\t\t${JSON.stringify(view.id)}: view${i},`);
	});
	const indent = (v: unknown) => tsString(v).replace(/\n/g, "\n\t");
	files.set(
		"forge_modules/views/registry.ts",
		[
			`${TS_BANNER}import { createViewRegistry } from "../ui/views.ts";`,
			...imports,
			"",
			"export const views = createViewRegistry({",
			"\tmodules: {",
			...modules,
			"\t},",
			`\tpanelTitles: ${indent(panelTitles)},`,
			`\tviews: ${indent(views)},`,
			"});",
			"",
			"/** Wrap a tool definition so results with details.view render as that view. */",
			"export const withViews = views.withViews;",
			'export { viewResult } from "./contract.ts";',
			"",
		].join("\n"),
	);
	files.set(
		"extensions/forge-views.ts",
		`${TS_BANNER}import { views } from "../forge_modules/views/registry.ts";\n\nexport default views.extension;\n`,
	);

	// Plan: the built-in update_plan tool (a live checklist in the terminal and in the web UI's side card).
	const planEnabled = spec.tools?.plan !== false;
	if (planEnabled) {
		copyTemplate("plan/plan.ts");
		for (const file of listFiles(join(TEMPLATES_DIR, "views", "plan"))) copyTemplate(`views/plan/${file}`);
		files.set("extensions/forge-plan.ts", `${TS_BANNER}import { createPlan } from "../forge_modules/plan/plan.ts";\n\nexport default createPlan();\n`);
	}

	// System prompt addition: the spec's text, the plan habit, and how views reach the user.
	const promptParts: string[] = [];
	if (spec.prompt?.system) promptParts.push(spec.prompt.system.trim());
	if (planEnabled) {
		promptParts.push(
			"## Plans\n\nFor any task with more than two steps, call `update_plan` before you start, with the whole checklist (first step in_progress). " +
				"After each step, call it again with the full list: mark finished steps done and the next one in_progress. Keep steps short and concrete. " +
				"The user watches this checklist beside the chat, so keep it honest: never mark a step done before it is.",
		);
	}
	if (views.length > 0) {
		const lines = views.map((v) => `- ${v.shows.map((s) => `\`${s}\``).join(", ")} → shown as a **${v.id}** view${v.panel ? " (also pinned as a panel)" : ""}`);
		promptParts.push(
			`## What the user sees\n\nSome tool results are shown to the user visually, not as text:\n${lines.join("\n")}\n\nDon't repeat what a view already shows (full tables, every property). Summarize what matters.`,
		);
	}
	if (promptParts.length > 0) files.set("APPEND_SYSTEM.md", `${promptParts.join("\n\n")}\n`);

	for (const path of files.keys()) {
		if (PROTECTED.some((re) => re.test(path))) throw new Error(`generator bug: planned protected path ${path}`);
	}
	return files;
}

// =============================================================================
// Plan / apply
// =============================================================================

export function planHarness(harnessDir: string): GenPlan {
	const dir = resolve(harnessDir);
	const ctx: ValidateContext = { templatesDir: TEMPLATES_DIR, harnessDir: dir, piVersion: installedPiVersion() };
	const result = validateSpec(readSpecFile(dir), ctx);
	if (!result.ok || !result.spec) return { harnessDir: dir, issues: result.issues, files: new Map(), changes: [] };

	const spec = result.spec;
	const issues = result.issues;

	const files = planFiles(spec, dir);
	const manifest = readManifest(dir);
	const changes: Change[] = [];

	for (const [path, content] of files) {
		const target = join(dir, path);
		if (!existsSync(target)) {
			changes.push({ path, kind: "add", added: content.split("\n").length - 1, removed: 0 });
			continue;
		}
		const current = normalize(readFileSync(target, "utf8"));
		if (current === content) {
			changes.push({ path, kind: "unchanged", added: 0, removed: 0 });
			continue;
		}
		let added = 0;
		let removed = 0;
		for (const part of diffLines(current, content)) {
			if (part.added) added += part.count ?? 0;
			if (part.removed) removed += part.count ?? 0;
		}
		const recorded = manifest?.files[path];
		const conflict =
			recorded === undefined
				? "exists but was not written by forge"
				: recorded !== sha(current)
					? "edited by hand since the last generate"
					: undefined;
		changes.push({ path, kind: "update", conflict, added, removed, patch: createTwoFilesPatch(path, path, current, content) });
	}

	for (const [path, recorded] of Object.entries(manifest?.files ?? {})) {
		const target = join(dir, path);
		if (files.has(path) || !existsSync(target)) continue;
		const current = readFileSync(target, "utf8");
		const conflict = recorded !== sha(current) ? "no longer generated, but edited by hand" : undefined;
		changes.push({ path, kind: "delete", conflict, added: 0, removed: normalize(current).split("\n").length - 1 });
	}

	changes.sort((a, b) => a.path.localeCompare(b.path));
	return { harnessDir: dir, spec, issues, files, changes };
}

export interface ApplyResult {
	written: string[];
	deleted: string[];
}

export function applyPlan(plan: GenPlan, options: { force?: boolean } = {}): ApplyResult {
	if (!plan.spec || plan.issues.some((i) => i.severity === "error")) throw new Error("harness.yaml has errors; fix them first");
	const conflicts = plan.changes.filter((c) => c.conflict);
	if (conflicts.length > 0 && !options.force) {
		throw new Error(`Refusing to overwrite:\n${conflicts.map((c) => `  ${c.path}: ${c.conflict}`).join("\n")}\nMove your changes to custom/ or pass force.`);
	}

	const written: string[] = [];
	const deleted: string[] = [];
	for (const change of plan.changes) {
		const target = join(plan.harnessDir, change.path);
		if (change.kind === "add" || change.kind === "update") {
			mkdirSync(dirname(target), { recursive: true });
			writeFileSync(target, plan.files.get(change.path) ?? "");
			written.push(change.path);
		} else if (change.kind === "delete") {
			rmSync(target, { force: true });
			deleted.push(change.path);
			removeEmptyParents(plan.harnessDir, dirname(target));
		}
	}

	// Folders for hand-written code; created once, never managed.
	for (const sub of ["custom/extensions", "custom/skills", "custom/views", "custom/lib"]) {
		const d = join(plan.harnessDir, sub);
		if (!existsSync(d)) {
			mkdirSync(d, { recursive: true });
			writeFileSync(join(d, ".gitkeep"), "");
		}
	}

	const manifest: Manifest = {
		generator: GENERATOR_VERSION,
		files: Object.fromEntries([...plan.files].map(([path, content]) => [path, sha(content)])),
	};
	mkdirSync(join(plan.harnessDir, ".forge"), { recursive: true });
	writeFileSync(join(plan.harnessDir, MANIFEST), json(manifest));
	return { written, deleted };
}

function removeEmptyParents(root: string, dir: string): void {
	let current = dir;
	while (current.startsWith(root) && current !== root && existsSync(current) && statSync(current).isDirectory()) {
		if (readdirSync(current).length > 0) return;
		rmSync(current, { recursive: true });
		current = dirname(current);
	}
}

/** Human-readable summary of a plan, used by the CLI and the forge_generate tool. */
export function formatPlan(plan: GenPlan): string {
	const lines: string[] = [];
	const errors = plan.issues.filter((i) => i.severity === "error");
	for (const issue of plan.issues) lines.push(`${issue.severity === "error" ? "✗" : "!"} ${issue.path}: ${issue.message}`);
	if (errors.length > 0) return lines.join("\n");

	const counts = { add: 0, update: 0, delete: 0, unchanged: 0 };
	for (const c of plan.changes) counts[c.kind]++;
	lines.push(
		`${relative(REPO_ROOT, plan.harnessDir) || "."}: ${counts.add} new, ${counts.update} changed, ${counts.delete} removed, ${counts.unchanged} unchanged`,
	);
	for (const c of plan.changes.filter((c) => c.kind !== "unchanged")) {
		const sign = c.kind === "add" ? "+" : c.kind === "delete" ? "-" : "~";
		lines.push(`  ${sign} ${c.path}  (+${c.added} -${c.removed})${c.conflict ? `  ⚠ ${c.conflict}` : ""}`);
	}
	return lines.join("\n");
}

export { themeName };

export { type LiveCheck, type LoadCheck, liveCheck, loadCheck } from "./smoke.ts";
