// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createSandbox } from "../forge_modules/guards/sandbox.ts";

export default createSandbox("off");
