// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createGuards } from "../forge_modules/guards/guards.ts";

export default createGuards({
	"protectedPaths": [
		".env",
		"**/forge_modules/**",
		"**/extensions/forge-*.ts",
		"**/.forge/**"
	],
	"confirmBash": [
		"rm -rf",
		"git push --force",
		"Remove-Item -Recurse",
		"git reset --hard"
	]
});
