// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createHeader } from "../forge_modules/ui/header.ts";

export default createHeader({
	"name": "forge",
	"title": "pi-Forge",
	"description": "Builds, validates, and updates agent harnesses",
	"hint": "Try: build me a harness for <your work> · list harnesses · what views exist?",
	"art": [
		"  ▄▄▄▄▄▄▄▄▄",
		"  ▀▀█████▀▀",
		"    ▄███▄",
		"   ▀▀▀▀▀▀▀"
	]
});
