// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { views } from "../forge_modules/views/registry.ts";

export default views.extension;
