// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createHeader } from "../forge_modules/ui/header.ts";

export default createHeader({
	"name": "loan-calc",
	"title": "Loan Calc",
	"description": "Loan amortization schedules and loan scenario comparison, pure calculation.",
	"hint": "Try: compare a 300k loan at 6.5% over 30 years vs 15 years at 5.9%",
	"art": [
		"      ▂▄",
		"   ▂▄▆██",
		"  ▆█████▇"
	]
});
