// Generated by forge from harness.yaml. Do not edit: run `forge-gen` instead. Your own code goes in custom/.
import { createViewRegistry } from "../ui/views.ts";
import * as view0 from "./chart/tui.ts";

export const views = createViewRegistry({
	modules: {
		"chart": view0,
	},
	panelTitles: {
		"chart": "latest chart"
	},
	views: [
		{
			"id": "chart",
			"shows": [
				"loan_schedule",
				"compare_loans"
			],
			"panel": "right"
		}
	],
});

/** Wrap a tool definition so results with details.view render as that view. */
export const withViews = views.withViews;
export { viewResult } from "./contract.ts";
